version: 0.2
phases:
  install:
    commands:
      - go version && go get -u -v golang.org/x/vgo
  build:
    commands:
      - cd go
      - echo $CODEBUILD_SRC_DIR_github_artifacts
      - echo $REPOSITORY_URI
      - make
artifacts:
  go_artifacts:
    files:
      - '**/*'
    base-directory: go/artifacts