Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  CodeBucket:
    Type: String
    Description: Bucket uri that code lives in.
Resources:
  Dispatch:
    Type: AWS::Serverless::Fucntion
    Properties:
      Handler: lambda
      Runtime: go1.x
      CodeUri: !Sub ${CodeBucket}/artifacts/cmd/dispatch/lambda
