AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  Dispatch:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda
      Runtime: go1.x
      CodeUri: ./goarts/cmd/renwick/dispatch/lambda #../../go/artifacts/cmd/dispatch/lambda
      Environment:
        Variables:
            SLACK_OAUTH: renwick/slack/oauth
      Events:
        SlackApi:
          Type: Api
          Properties: 
            Path: /slack_event
            Method: POST
